---
git-uri: https://github.com/pivotal-bank/accounts-service.git
git-branch: development
cf-api-uri: cf-api-uri
cf-skip-ssl: true
cf-username: username
cf-password: password
cf-org: org
cf-space: dev
cf-config-server-uri: https://github.com/pivotal-bank/cf-SpringBootTrader-config
cf-config-server-label: master
cf-config-server-plan: standard
cf-circuit-breaker-dashboard-plan: standard
cf-service-registry-plan: standard
cf-db-service: p-mysql
cf-db-service-plan: pre-existing-plan
cf-db-service-name: traderdb
