info:
  component: Config Server
spring:
  application:
    name: configserver
  profiles:
    active: native
  jmx:
    default_domain: cloud.config.server
  cloud:
    config:
      server:
        native:
          searchLocations: file:${user.dir}/../cf-SpringBootTrader-config
management:
  context_path: /admin
server:
  port: 8888
